### ISSUE TITLE
NPE when starting roda-in

### ISSUE THREAD

**Issue by hsilva-keep** [keeps/roda-in#217]
**roda-in version**: alpha8
```java
java.lang.NullPointerException: null
	at java.text.SimpleDateFormat.parse(SimpleDateFormat.java:1439)
	at java.text.DateFormat.parse(DateFormat.java:364)
	at org.roda.rodain.utils.Utils.getCurrentVersionBuildDate(Utils.java:211)
	at org.roda.rodain.core.RodaIn.checkForUpdates(RodaIn.java:608)
	at org.roda.rodain.core.RodaIn.lambda$start$0(RodaIn.java:198)
	at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
	at javafx.event.Event.fireEvent(Event.java:198)
	at javafx.concurrent.EventHelper.fireEvent(EventHelper.java:219)
	at javafx.concurrent.Task.fireEvent(Task.java:1356)
	at javafx.concurrent.Task.setState(Task.java:723)
	at javafx.concurrent.Task$TaskCallable.lambda$call$500(Task.java:1434)
	at com.sun.javafx.application.PlatformImpl.lambda$null$173(PlatformImpl.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$174(PlatformImpl.java:294)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at com.sun.glass.ui.gtk.GtkApplication.lambda$null$49(GtkApplication.java:139)
	at java.lang.Thread.run(Thread.java:745)
```

**roda-in version**: 4c6960690c86405addeb53cefb12df86fd66491b
```java
java.lang.NullPointerException: null
	at java.text.SimpleDateFormat.parse(SimpleDateFormat.java:1439)
	at java.text.DateFormat.parse(DateFormat.java:364)
	at org.roda.rodain.utils.Utils.getCurrentVersionBuildDate(Utils.java:213)
	at org.roda.rodain.core.RodaIn.checkForUpdates(RodaIn.java:607)
	at org.roda.rodain.core.RodaIn.lambda$start$0(RodaIn.java:198)
	at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
	at javafx.event.Event.fireEvent(Event.java:198)
	at javafx.concurrent.EventHelper.fireEvent(EventHelper.java:219)
	at javafx.concurrent.Task.fireEvent(Task.java:1356)
	at javafx.concurrent.Task.setState(Task.java:723)
	at javafx.concurrent.Task$TaskCallable.lambda$call$500(Task.java:1434)
	at com.sun.javafx.application.PlatformImpl.lambda$null$173(PlatformImpl.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$174(PlatformImpl.java:294)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at com.sun.glass.ui.gtk.GtkApplication.lambda$null$49(GtkApplication.java:139)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by hsilva-keep** [comment]
The problem is due to the way the configuration is read. The following line (Utils.java:209)
```java
PropertiesConfiguration pc = new PropertiesConfiguration(BUILD_PROPERTIES_FILE);
```
tries to read a file called `build.properties` without specifying from where. The commons-configuration library then tries to find this file. After doing some debug, one of the first places where it tries to find the file is in USER_HOME, which in my case had a file called `build.properties` but from another software, which caused roda-in to get a property and assuming that the property had a value which in this case didn't happened.

**Comment by sleroux-keep** [comment]
Fixed
