### ISSUE TITLE
Error exporting SIPs that have been multiple edited

### ISSUE THREAD

**Issue by luis100** [keeps/roda-in#218]
If multiple SIPs are selected and something changed, when exporting the following error occurs:

```
2016-11-15 13:22:28,399 [Thread-32] ERROR o.r.rodain.creation.EarkSipCreator - Commons IP exception
org.roda_project.commons_ip.utils.SIPException: Error generating E-ARK SIP ZIP file. Reason: duplicate entry: schemas/dc.xsd
	at org.roda_project.commons_ip.model.impl.eark.EARKSIP.build(EARKSIP.java:141)
	at org.roda.rodain.creation.EarkSipCreator.createEarkSip(EarkSipCreator.java:176)
	at org.roda.rodain.creation.EarkSipCreator.run(EarkSipCreator.java:80)
Caused by: org.roda_project.commons_ip.utils.SIPException: Error generating E-ARK SIP ZIP file. Reason: duplicate entry: schemas/dc.xsd
	at org.roda_project.commons_ip.model.impl.eark.EARKSIP.createZipFile(EARKSIP.java:406)
	at org.roda_project.commons_ip.model.impl.eark.EARKSIP.build(EARKSIP.java:134)
	... 2 common frames omitted
Caused by: java.util.zip.ZipException: duplicate entry: schemas/dc.xsd
	at java.util.zip.ZipOutputStream.putNextEntry(ZipOutputStream.java:233)
	at org.roda_project.commons_ip.utils.ZIPUtils.zip(ZIPUtils.java:116)
	at org.roda_project.commons_ip.utils.ZIPUtils.zipWhileCalculatingChecksum(ZIPUtils.java:99)
	at org.roda_project.commons_ip.model.impl.eark.EARKSIP.createZipFile(EARKSIP.java:402)
	... 3 common frames omitted
```

**Comment by sleroux-keep** [comment]
Fixed
