### ISSUE TITLE
InvalidPathException for files under UNC path

### ISSUE THREAD

**Issue by DenysShvorack** [keeps/roda-in#322]
When files for association are under UNC path then the association process does not happen and no messages are shown.

In the logs there is InvalidPathException:

>  13:47:01 ERROR org.roda.rodain.ui.RodaInApplication - An unexpected error occurred in Thread[Thread-11,5,main]
java.nio.file.InvalidPathException: UNC path is missing sharename: \\\\vserver.ch
    at sun.nio.fs.WindowsPathParser.parse(Unknown Source)
    at sun.nio.fs.WindowsPathParser.parse(Unknown Source)
    at sun.nio.fs.WindowsPath.parse(Unknown Source)
    at sun.nio.fs.WindowsFileSystem.getPath(Unknown Source)
    at java.nio.file.Paths.get(Unknown Source)
    at org.roda.rodain.core.rules.filters.ContentFilter.filter(ContentFilter.java:101)
    at org.roda.rodain.core.sip.creators.SipPreviewCreator.filter(SipPreviewCreator.java:152)
    at org.roda.rodain.core.sip.creators.SipSingle.preVisitDirectory(SipSingle.java:56)
    at org.roda.rodain.core.utils.WalkFileTree$1.preVisitDirectory(WalkFileTree.java:67)
    at org.roda.rodain.core.utils.WalkFileTree$1.preVisitDirectory(WalkFileTree.java:57)
    at java.nio.file.Files.walkFileTree(Unknown Source)
    at java.nio.file.Files.walkFileTree(Unknown Source)
    at org.roda.rodain.core.utils.WalkFileTree.run(WalkFileTree.java:57)

I made a fix in my fork in this commit:
https://github.com/DenysShvorack/roda-in/commit/ccc4dceebb7d0efe201e7bcb663d55458fe717be

After which association and SIP creation process where performed succesfully.

**Comment by luis100** [comment]
Hi @DenysShvorack , thank you for your contribution! Could you make a [pull request](https://help.github.com/articles/creating-a-pull-request-from-a-fork/) so we can follow procedure?

**Comment by DenysShvorack** [comment]
Hi @luis100 , just created a [pull request](https://github.com/keeps/roda-in/pull/323)

**Comment by hsilva-keep** [comment]
Fixed since https://github.com/keeps/roda-in/releases/tag/v2.2.0
