### ISSUE TITLE
Folder name with trailing white space can't be turned into IP

### ISSUE THREAD

**Issue by JelleKleevensVAI** [keeps/roda-in#359]
Path name of folder with trailing whitespace:
"C:\Users\VAIJelleKleevens\Downloads\TestFilesCK\CKA_REFERENTIEBEELDEN\CK REIZEN_04-\AALST 200406 WONING PDB "

Log:
ERROR org.roda.rodain.ui.RodaInApplication - An unexpected error occurred in Thread[Thread-61,5,main]
java.nio.file.InvalidPathException: Trailing char < > at index 107: C:\Users\VAIJelleKleevens\Downloads\TestFilesCK\CKA_REFERENTIEBEELDEN\CK REIZEN_04-\AALST 200406 WONING PDB 
	at java.base/sun.nio.fs.WindowsPathParser.normalize(Unknown Source) ~[na:na]
	at java.base/sun.nio.fs.WindowsPathParser.parse(Unknown Source) ~[na:na]
	at java.base/sun.nio.fs.WindowsPathParser.parse(Unknown Source) ~[na:na]
	at java.base/sun.nio.fs.WindowsPath.parse(Unknown Source) ~[na:na]
	at java.base/sun.nio.fs.WindowsFileSystem.getPath(Unknown Source) ~[na:na]
	at java.base/java.nio.file.Path.of(Unknown Source) ~[na:na]
	at java.base/java.nio.file.Paths.get(Unknown Source) ~[na:na]
	at org.roda.rodain.core.rules.filters.ContentFilter.filter(ContentFilter.java:84) ~[RODA-in.exe:na]
	at org.roda.rodain.core.sip.creators.SipPreviewCreator.filter(SipPreviewCreator.java:152) ~[RODA-in.exe:na]
	at org.roda.rodain.core.sip.creators.SipPerSelection.filter(SipPerSelection.java:49) ~[RODA-in.exe:na]
	at org.roda.rodain.core.sip.creators.SipPerSelection.preVisitDirectory(SipPerSelection.java:74) ~[RODA-in.exe:na]
	at org.roda.rodain.core.utils.WalkFileTree$1.preVisitDirectory(WalkFileTree.java:67) ~[RODA-in.exe:na]
	at org.roda.rodain.core.utils.WalkFileTree$1.preVisitDirectory(WalkFileTree.java:57) ~[RODA-in.exe:na]
	at java.base/java.nio.file.Files.walkFileTree(Unknown Source) ~[na:na]
	at java.base/java.nio.file.Files.walkFileTree(Unknown Source) ~[na:na]
	at org.roda.rodain.core.utils.WalkFileTree.run(WalkFileTree.java:57) ~[RODA-in.exe:na]

**Comment by JoaoGomes2110** [comment]
Do not end a file or directory name with a space or a period. Although the underlying file system may support such names, the Windows shell and user interface does not. However, it is acceptable to specify a period as the first character of a name. For example, ".temp".

See:  https://keep-solutions.slack.com/archives/D0212QNBUD8/p1629298734008300

**Comment by JelleKleevensVAI** [comment]
Is there a possible workaround? Because this means we need to manually or via script adapt these files. However, this is not ideal because these actions are not logged in PREMIS.

On linux we don't have this issue, ideally RODA-In has the same behaviour on all platforms.
