### ISSUE TITLE
Error while running tests

### ISSUE THREAD

**Issue by luis100** [keeps/roda-in#67]
When running `mvn clean package` on a desktop machine the following tests fail.

```
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running org.roda.rodain.source.ui.FileExplorerPaneTest
Tests run: 5, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 26.476 sec - in org.roda.rodain.source.ui.FileExplorerPaneTest
Running org.roda.rodain.source.ui.IgnoreTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 12.153 sec - in org.roda.rodain.source.ui.IgnoreTest
Running org.roda.rodain.core.MainTest
2016-01-06 10:13:59,152 [JavaFX Application Thread] ERROR org.roda.rodain.schema.ui.SchemaPane - Error creating the scheme tree
org.roda.rodain.schema.ui.MalformedSchemaException: The node "TFLF" has 0 parents
	at org.roda.rodain.schema.ui.SchemaPane.updateClassificationSchema(SchemaPane.java:237) [classes/:na]
	at org.roda.rodain.schema.ui.SchemaPane.loadClassificationSchemeFromStream(SchemaPane.java:194) [classes/:na]
	at org.roda.rodain.core.MainTest.start(MainTest.java:41) [test-classes/:na]
	at org.testfx.toolkit.impl.ApplicationServiceImpl.lambda$start$71(ApplicationServiceImpl.java:68) [testfx-core-4.0.1-alpha.jar:4.0.1-alpha]
	at org.testfx.util.WaitForAsyncUtils.callCallableAndSetFuture(WaitForAsyncUtils.java:336) ~[testfx-core-4.0.1-alpha.jar:4.0.1-alpha]
	at org.testfx.util.WaitForAsyncUtils.lambda$asyncFx$13(WaitForAsyncUtils.java:104) ~[testfx-core-4.0.1-alpha.jar:4.0.1-alpha]
	at com.sun.javafx.application.PlatformImpl.lambda$null$173(PlatformImpl.java:295) ~[jfxrt.jar:na]
	at java.security.AccessController.doPrivileged(Native Method) ~[na:1.8.0_66]
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$174(PlatformImpl.java:294) ~[jfxrt.jar:na]
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95) ~[jfxrt.jar:na]
	at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method) ~[jfxrt.jar:na]
	at com.sun.glass.ui.gtk.GtkApplication.lambda$null$49(GtkApplication.java:139) ~[jfxrt.jar:na]
	at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_66]
2016-01-06 10:13:59,154 [JavaFX Application Thread] ERROR org.roda.rodain.schema.ui.SchemaPane - Error creating the scheme tree
org.roda.rodain.schema.ui.MalformedSchemaException: The node "TLC" has 0 parents
	at org.roda.rodain.schema.ui.SchemaPane.updateClassificationSchema(SchemaPane.java:237) [classes/:na]
	at org.roda.rodain.schema.ui.SchemaPane.loadClassificationSchemeFromStream(SchemaPane.java:194) [classes/:na]
	at org.roda.rodain.core.MainTest.start(MainTest.java:41) [test-classes/:na]
	at org.testfx.toolkit.impl.ApplicationServiceImpl.lambda$start$71(ApplicationServiceImpl.java:68) [testfx-core-4.0.1-alpha.jar:4.0.1-alpha]
	at org.testfx.util.WaitForAsyncUtils.callCallableAndSetFuture(WaitForAsyncUtils.java:336) ~[testfx-core-4.0.1-alpha.jar:4.0.1-alpha]
	at org.testfx.util.WaitForAsyncUtils.lambda$asyncFx$13(WaitForAsyncUtils.java:104) ~[testfx-core-4.0.1-alpha.jar:4.0.1-alpha]
	at com.sun.javafx.application.PlatformImpl.lambda$null$173(PlatformImpl.java:295) ~[jfxrt.jar:na]
	at java.security.AccessController.doPrivileged(Native Method) ~[na:1.8.0_66]
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$174(PlatformImpl.java:294) ~[jfxrt.jar:na]
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95) ~[jfxrt.jar:na]
	at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method) ~[jfxrt.jar:na]
	at com.sun.glass.ui.gtk.GtkApplication.lambda$null$49(GtkApplication.java:139) ~[jfxrt.jar:na]
	at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_66]
2016-01-06 10:13:59,163 [JavaFX Application Thread] ERROR org.roda.rodain.schema.ui.SchemaPane - Error creating the scheme tree
org.roda.rodain.schema.ui.MalformedSchemaException: The node "TTRC" has 0 parents
	at org.roda.rodain.schema.ui.SchemaPane.updateClassificationSchema(SchemaPane.java:237) [classes/:na]
	at org.roda.rodain.schema.ui.SchemaPane.loadClassificationSchemeFromStream(SchemaPane.java:194) [classes/:na]
	at org.roda.rodain.core.MainTest.start(MainTest.java:41) [test-classes/:na]
	at org.testfx.toolkit.impl.ApplicationServiceImpl.lambda$start$71(ApplicationServiceImpl.java:68) [testfx-core-4.0.1-alpha.jar:4.0.1-alpha]
	at org.testfx.util.WaitForAsyncUtils.callCallableAndSetFuture(WaitForAsyncUtils.java:336) ~[testfx-core-4.0.1-alpha.jar:4.0.1-alpha]
	at org.testfx.util.WaitForAsyncUtils.lambda$asyncFx$13(WaitForAsyncUtils.java:104) ~[testfx-core-4.0.1-alpha.jar:4.0.1-alpha]
	at com.sun.javafx.application.PlatformImpl.lambda$null$173(PlatformImpl.java:295) ~[jfxrt.jar:na]
	at java.security.AccessController.doPrivileged(Native Method) ~[na:1.8.0_66]
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$174(PlatformImpl.java:294) ~[jfxrt.jar:na]
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95) ~[jfxrt.jar:na]
	at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method) ~[jfxrt.jar:na]
	at com.sun.glass.ui.gtk.GtkApplication.lambda$null$49(GtkApplication.java:139) ~[jfxrt.jar:na]
	at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_66]
2016-01-06 10:13:59,163 [JavaFX Application Thread] ERROR org.roda.rodain.schema.ui.SchemaPane - Error creating the scheme tree
org.roda.rodain.schema.ui.MalformedSchemaException: The node "TMSe" has 0 parents
	at org.roda.rodain.schema.ui.SchemaPane.updateClassificationSchema(SchemaPane.java:237) [classes/:na]
	at org.roda.rodain.schema.ui.SchemaPane.loadClassificationSchemeFromStream(SchemaPane.java:194) [classes/:na]
	at org.roda.rodain.core.MainTest.start(MainTest.java:41) [test-classes/:na]
	at org.testfx.toolkit.impl.ApplicationServiceImpl.lambda$start$71(ApplicationServiceImpl.java:68) [testfx-core-4.0.1-alpha.jar:4.0.1-alpha]
	at org.testfx.util.WaitForAsyncUtils.callCallableAndSetFuture(WaitForAsyncUtils.java:336) ~[testfx-core-4.0.1-alpha.jar:4.0.1-alpha]
	at org.testfx.util.WaitForAsyncUtils.lambda$asyncFx$13(WaitForAsyncUtils.java:104) ~[testfx-core-4.0.1-alpha.jar:4.0.1-alpha]
	at com.sun.javafx.application.PlatformImpl.lambda$null$173(PlatformImpl.java:295) ~[jfxrt.jar:na]
	at java.security.AccessController.doPrivileged(Native Method) ~[na:1.8.0_66]
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$174(PlatformImpl.java:294) ~[jfxrt.jar:na]
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95) ~[jfxrt.jar:na]
	at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method) ~[jfxrt.jar:na]
	at com.sun.glass.ui.gtk.GtkApplication.lambda$null$49(GtkApplication.java:139) ~[jfxrt.jar:na]
	at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_66]
2016-01-06 10:14:01,125 [JavaFX Application Thread] ERROR org.roda.rodain.schema.ui.SchemaPane - Error creating the scheme tree
org.roda.rodain.schema.ui.MalformedSchemaException: The node "TFLF" has 0 parents
	at org.roda.rodain.schema.ui.SchemaPane.updateClassificationSchema(SchemaPane.java:237) [classes/:na]
	at org.roda.rodain.schema.ui.SchemaPane.loadClassificationSchemeFromStream(SchemaPane.java:194) [classes/:na]
	at org.roda.rodain.core.MainTest.start(MainTest.java:41) [test-classes/:na]
	at org.testfx.toolkit.impl.ApplicationServiceImpl.lambda$start$71(ApplicationServiceImpl.java:68) [testfx-core-4.0.1-alpha.jar:4.0.1-alpha]
	at org.testfx.util.WaitForAsyncUtils.callCallableAndSetFuture(WaitForAsyncUtils.java:336) ~[testfx-core-4.0.1-alpha.jar:4.0.1-alpha]
	at org.testfx.util.WaitForAsyncUtils.lambda$asyncFx$13(WaitForAsyncUtils.java:104) ~[testfx-core-4.0.1-alpha.jar:4.0.1-alpha]
	at com.sun.javafx.application.PlatformImpl.lambda$null$173(PlatformImpl.java:295) ~[jfxrt.jar:na]
	at java.security.AccessController.doPrivileged(Native Method) ~[na:1.8.0_66]
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$174(PlatformImpl.java:294) ~[jfxrt.jar:na]
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95) ~[jfxrt.jar:na]
	at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method) ~[jfxrt.jar:na]
	at com.sun.glass.ui.gtk.GtkApplication.lambda$null$49(GtkApplication.java:139) ~[jfxrt.jar:na]
	at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_66]
2016-01-06 10:14:01,126 [JavaFX Application Thread] ERROR org.roda.rodain.schema.ui.SchemaPane - Error creating the scheme tree
org.roda.rodain.schema.ui.MalformedSchemaException: The node "TLC" has 0 parents
	at org.roda.rodain.schema.ui.SchemaPane.updateClassificationSchema(SchemaPane.java:237) [classes/:na]
	at org.roda.rodain.schema.ui.SchemaPane.loadClassificationSchemeFromStream(SchemaPane.java:194) [classes/:na]
	at org.roda.rodain.core.MainTest.start(MainTest.java:41) [test-classes/:na]
	at org.testfx.toolkit.impl.ApplicationServiceImpl.lambda$start$71(ApplicationServiceImpl.java:68) [testfx-core-4.0.1-alpha.jar:4.0.1-alpha]
	at org.testfx.util.WaitForAsyncUtils.callCallableAndSetFuture(WaitForAsyncUtils.java:336) ~[testfx-core-4.0.1-alpha.jar:4.0.1-alpha]
	at org.testfx.util.WaitForAsyncUtils.lambda$asyncFx$13(WaitForAsyncUtils.java:104) ~[testfx-core-4.0.1-alpha.jar:4.0.1-alpha]
	at com.sun.javafx.application.PlatformImpl.lambda$null$173(PlatformImpl.java:295) ~[jfxrt.jar:na]
	at java.security.AccessController.doPrivileged(Native Method) ~[na:1.8.0_66]
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$174(PlatformImpl.java:294) ~[jfxrt.jar:na]
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95) ~[jfxrt.jar:na]
	at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method) ~[jfxrt.jar:na]
	at com.sun.glass.ui.gtk.GtkApplication.lambda$null$49(GtkApplication.java:139) ~[jfxrt.jar:na]
	at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_66]
2016-01-06 10:14:01,128 [JavaFX Application Thread] ERROR org.roda.rodain.schema.ui.SchemaPane - Error creating the scheme tree
org.roda.rodain.schema.ui.MalformedSchemaException: The node "TTRC" has 0 parents
	at org.roda.rodain.schema.ui.SchemaPane.updateClassificationSchema(SchemaPane.java:237) [classes/:na]
	at org.roda.rodain.schema.ui.SchemaPane.loadClassificationSchemeFromStream(SchemaPane.java:194) [classes/:na]
	at org.roda.rodain.core.MainTest.start(MainTest.java:41) [test-classes/:na]
	at org.testfx.toolkit.impl.ApplicationServiceImpl.lambda$start$71(ApplicationServiceImpl.java:68) [testfx-core-4.0.1-alpha.jar:4.0.1-alpha]
	at org.testfx.util.WaitForAsyncUtils.callCallableAndSetFuture(WaitForAsyncUtils.java:336) ~[testfx-core-4.0.1-alpha.jar:4.0.1-alpha]
	at org.testfx.util.WaitForAsyncUtils.lambda$asyncFx$13(WaitForAsyncUtils.java:104) ~[testfx-core-4.0.1-alpha.jar:4.0.1-alpha]
	at com.sun.javafx.application.PlatformImpl.lambda$null$173(PlatformImpl.java:295) ~[jfxrt.jar:na]
	at java.security.AccessController.doPrivileged(Native Method) ~[na:1.8.0_66]
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$174(PlatformImpl.java:294) ~[jfxrt.jar:na]
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95) ~[jfxrt.jar:na]
	at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method) ~[jfxrt.jar:na]
	at com.sun.glass.ui.gtk.GtkApplication.lambda$null$49(GtkApplication.java:139) ~[jfxrt.jar:na]
	at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_66]
2016-01-06 10:14:01,128 [JavaFX Application Thread] ERROR org.roda.rodain.schema.ui.SchemaPane - Error creating the scheme tree
org.roda.rodain.schema.ui.MalformedSchemaException: The node "TMSe" has 0 parents
	at org.roda.rodain.schema.ui.SchemaPane.updateClassificationSchema(SchemaPane.java:237) [classes/:na]
	at org.roda.rodain.schema.ui.SchemaPane.loadClassificationSchemeFromStream(SchemaPane.java:194) [classes/:na]
	at org.roda.rodain.core.MainTest.start(MainTest.java:41) [test-classes/:na]
	at org.testfx.toolkit.impl.ApplicationServiceImpl.lambda$start$71(ApplicationServiceImpl.java:68) [testfx-core-4.0.1-alpha.jar:4.0.1-alpha]
	at org.testfx.util.WaitForAsyncUtils.callCallableAndSetFuture(WaitForAsyncUtils.java:336) ~[testfx-core-4.0.1-alpha.jar:4.0.1-alpha]
	at org.testfx.util.WaitForAsyncUtils.lambda$asyncFx$13(WaitForAsyncUtils.java:104) ~[testfx-core-4.0.1-alpha.jar:4.0.1-alpha]
	at com.sun.javafx.application.PlatformImpl.lambda$null$173(PlatformImpl.java:295) ~[jfxrt.jar:na]
	at java.security.AccessController.doPrivileged(Native Method) ~[na:1.8.0_66]
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$174(PlatformImpl.java:294) ~[jfxrt.jar:na]
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95) ~[jfxrt.jar:na]
	at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method) ~[jfxrt.jar:na]
	at com.sun.glass.ui.gtk.GtkApplication.lambda$null$49(GtkApplication.java:139) ~[jfxrt.jar:na]
	at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_66]
Tests run: 2, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 7.031 sec <<< FAILURE! - in org.roda.rodain.core.MainTest
association(org.roda.rodain.core.MainTest)  Time elapsed: 4.102 sec  <<< ERROR!
java.lang.RuntimeException: java.lang.NullPointerException
	at org.testfx.service.locator.impl.BoundsLocatorImpl.makeSceneBounds(BoundsLocatorImpl.java:100)
	at org.testfx.service.locator.impl.BoundsLocatorImpl.limitToVisibleBounds(BoundsLocatorImpl.java:91)
	at org.testfx.service.locator.impl.BoundsLocatorImpl.boundsInSceneFor(BoundsLocatorImpl.java:39)
	at org.testfx.service.locator.impl.BoundsLocatorImpl.boundsOnScreenFor(BoundsLocatorImpl.java:60)
	at org.testfx.service.locator.impl.PointLocatorImpl.lambda$callableBoundsFor$67(PointLocatorImpl.java:89)
	at org.testfx.service.query.impl.CallableBoundsPointQuery.fetchCallableBounds(CallableBoundsPointQuery.java:62)
	at org.testfx.service.query.impl.CallableBoundsPointQuery.query(CallableBoundsPointQuery.java:49)
	at org.testfx.robot.impl.MoveRobotImpl.moveTo(MoveRobotImpl.java:78)
	at org.testfx.robot.impl.DragRobotImpl.dropTo(DragRobotImpl.java:70)
	at org.testfx.api.FxRobot.dropTo(FxRobot.java:751)
	at org.testfx.api.FxRobot.dropTo(FxRobot.java:867)
	at org.roda.rodain.core.MainTest.association(MainTest.java:75)


Results :

Tests in error: 
  MainTest.association:75->FxRobot.dropTo:867->FxRobot.dropTo:751 » Runtime java...

```

**Comment by adrapereira** [comment]
Fixed
